In [3]:
import numpy as np
from scipy.linalg import null_space
import sympy as sp
from sympy import Poly, symbols, Domain
from sympy import ZZ, QQ
from sympy.polys.domainmatrix import DomainMatrix
from sympy.polys.domains import GF


In [4]:
def cyclicshift(n, k):
    S = np.zeros((n, n), dtype = bool)
    for i in range(n):
        S[i, (i+k) % n] = True
    return S

def y(l, m, k):
    return np.kron(np.identity(l), cyclicshift(m, k))

def x(l, m, k):
    return np.kron(cyclicshift(l, k), np.identity(m))


In [5]:

def ker_of(arr):
    dm = DomainMatrix(arr.tolist(), arr.shape, domain=GF(2))
    return np.array(dm.nullspace().to_Matrix())
def nparr_to_lean(arr):
    s = "!!["
    for row in arr:
        for elem in row:
            s = s + str(elem)+","
        s = s[:-1] + ";\n"
    s = s + "]"
    return s


In [6]:
l = 6
m = 6
x(l, m, 3) + y(l, m, 3)
BB_72_A = x(l, m, 3)+y(l, m, 1)+y(l, m, 2)
BB_72_B = y(l, m, 3)+x(l, m, 1)+x(l, m, 2)
H_x = np.hstack((BB_72_A, BB_72_B))
H_z = np.hstack((BB_72_B.transpose(), BB_72_A.transpose()))


In [17]:
l = 4
m = 4
BB_72_A = x(l, m, 3)+y(l, m, 1)+y(l, m, 2)
BB_72_B = y(l, m, 3)+x(l, m, 1)+x(l, m, 2)
H_x = np.hstack((BB_72_A, BB_72_B))
H_z = np.hstack((BB_72_B.transpose(), BB_72_A.transpose()))

In [8]:

#print(nparr_to_lean(ker_of(H_z)))
print(ker_of(H_x))

[[0 1 1 0 1 1 1 0 1 1 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 1 1 1 0 1 1 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 1 1 0 1 1 1 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 1 1 0 1 1 1 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 1 0 1 1 1 0 1 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 1 1 0 1 1 1 0 1 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 1 0 0 1 1 0 1 1 1 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 1 1 0 0 1 1 0 1 1 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 1 0 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 1 1 1 1 0 0 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [1 0 1 1 0 1 0 0 1 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [1 1 0 1 0 0 1 0 1 1 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [1 1 1 0 1 1 1 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 1 1 1 0 1 1 1 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [1 0 1 1 1 0 1 1 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [9]:
q9x = np.array([[1, 1, 1, 1, 1, 1, 0, 0, 0], [0, 0, 0, 1, 1, 1, 1, 1, 1]])
q9z = np.array([[1, 1, 0, 0, 0, 0, 0, 0, 0],[0, 1, 1, 0, 0, 0, 0, 0, 0],[0, 0, 0, 1, 1, 0, 0, 0, 0],
  [0, 0, 0, 0, 1, 1, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 1, 1, 0],
  [0, 0, 0, 0, 0, 0, 0, 1, 1]
])
print(nparr_to_lean(ker_of(q9z)))

!![1,1,1,0,0,0,0,0,0;
0,0,0,1,1,1,0,0,0;
0,0,0,0,0,0,1,1,1;
]


In [10]:
steane = np.array([[1, 0, 0, 1, 0, 1, 1],
                    [0, 1, 0, 1, 1, 0 , 1],
                      [0, 0, 1, 0, 1, 1, 1]])
print(nparr_to_lean(ker_of(steane)))

!![1,1,0,1,0,0,0;
0,1,1,0,1,0,0;
1,0,1,0,0,1,0;
1,1,1,0,0,0,1;
]


In [11]:
golay = np.array([
    [0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],[
1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],[
0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],[
1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],[
1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],[
1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],[
0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],[
0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],[
0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],[
1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],[
1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

])

print(nparr_to_lean(ker_of(golay)))

!![1,1,0,0,0,1,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0;
0,1,1,0,0,0,1,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0;
1,1,1,1,0,1,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0;
0,1,1,1,1,0,1,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0;
0,0,1,1,1,1,0,1,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0;
1,1,0,1,1,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0;
0,1,1,0,1,1,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0;
0,0,1,1,0,1,1,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0;
1,1,0,1,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0;
1,0,1,0,1,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0;
1,0,0,1,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,1,0;
1,0,0,0,1,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1;
]


In [12]:
def matrix_to_nat(matrix):
    # 1. Flatten the m x n matrix into a 1D array of m*n indices
    # 'C' order (row-major) is standard: [row0, row1, ...]
    flattened = np.array(matrix).astype(int)[::-1,::-1].flatten()
    
    # 2. Convert the bits to a binary string
    bit_string = ''.join(map(str, flattened))
    
    # 3. Convert binary string to a natural number (base 2)
    natural_number = int(bit_string, 2)
    
    return hex(natural_number), natural_number, bit_string


In [13]:
print(matrix_to_nat(steane))
print(matrix_to_nat(ker_of(steane)))

('0x1d2d69', 1912169, '111010010110101101001')
('0x8e94b0b', 149506827, '1000111010010100101100001011')


In [14]:
print(matrix_to_nat(H_x))
print(matrix_to_nat(H_z))
print(matrix_to_nat(ker_of(H_x)))
print(matrix_to_nat(ker_of(H_z)))
print(H_x.shape)

('0x40883800204494001022c20080116100840803804204094021020c20180106108840003844200094221000c21180006108848003044240090221200c01181006', 3379820556433469037133355206251672184889733199260027950274869350730745478399865528576701701579963254349000795033610931411828984752808224688596959033298950, '01000000100010000011100000000000001000000100010010010100000000000001000000100010110000100000000010000000000100010110000100000000100001000000100000000011100000000100001000000100000010010100000000100001000000100000110000100000000110000000000100000110000100001000100001000000000000000011100001000100001000000000000010010100001000100001000000000000110000100001000110000000000000000110000100001000100001001000000000000011000001000100001001000000000010010000001000100001001000000000110000000001000110000001000000000110')
('0x600818803004844090024220c00121108600018843000844290004221c00021108608018043040840290204201c01021008688010043440800292204001c1102', 5029584249224872563034053066208833503203016178134205493295

In [15]:
def greedy_independent_rows(matrix):
    """
    Greedily selects rows from top to bottom that are linearly 
    independent over F2.
    """
    num_rows, num_cols = matrix.shape
    
    selected_indices = []
    basis = [] # Stores the rows that form our current basis

    for i in range(num_rows):
        row = matrix[i].copy()
        
        # Reduce the current row using the basis already found
        for b in basis:
            # If the row has a 1 at the pivot position of the basis row, XOR them
            # This is the standard Gaussian elimination step over F2
            pivot = np.argmax(b == 1)
            if row[pivot] == 1:
                row = (row + b) % 2
        
        # If the row is not all zeros after reduction, it is independent
        if np.any(row):
            selected_indices.append(i)
            # Add to basis and keep basis in row-echelon form for efficiency
            basis.append(row)
            # Optional: Sort basis by leading coefficient (pivot) to speed up reduction
            basis.sort(key=lambda x: np.argmax(x == 1))

    return selected_indices, matrix[selected_indices]

In [16]:
print(greedy_independent_rows(steane))

([0, 1, 2], array([[1, 0, 0, 1, 0, 1, 1],
       [0, 1, 0, 1, 1, 0, 1],
       [0, 0, 1, 0, 1, 1, 1]]))


In [83]:
def vec_to_bits(vec):
    bs = ''.join(map(str, vec[::-1]))
    return bs

def mulvec_bin(mat, vec):
    return (mat @ vec) % 2

def num_to_vec(num, width):
    return np.array(list(f"{num:0{width}b}"), dtype=int)

num = 18446744073709551616

print(num_to_vec(num, 72))
print(num_to_vec(590295814831914094592, 72))
print(mulvec_bin(H_x, num_to_vec(num, 72))[6])
print(H_x[6])
print(H_x)
print(num_to_vec(116, 7))
print(H_x[31][::-1])




[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0
 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
1.0
[0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.
 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 1. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[1 1 1 0 1 0 0]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
print(hex(serialize_matrix(H_z)))
print(H_z.shape)
print(hex(serialize_matrix(ker_of(H_x))))
print(ker_of(H_x).shape)

0x38009400c2006100038009400c2006100038009400c2006180034009200c10064088204410228011840842042102180188404420221011800884044202210118
(16, 32)
0x80004000200010000800040002000100008000400020001000080004000200016ee137789bb4cdd216ee837749bb2cdde16e7837b49bd2cdee167783bb49dd2c
(16, 32)


In [12]:
print(hex(serialize_matrix(steane)))
print(steane.shape)
print(hex(serialize_matrix(ker_of(steane))))
print(ker_of(steane))

0x1ee711
(3, 7)
0x8421ebd
[[1 1 0 1 0 0 0]
 [0 1 1 0 1 0 0]
 [1 0 1 0 0 1 0]
 [1 1 1 0 0 0 1]]


In [22]:
print(hex(serialize_matrix(golay)))
print(golay.shape)
print(hex(serialize_matrix(ker_of(golay))))


0x40100401004010040100401004008eb27ea5ee3366d9b661ed7b5ed18ee3a
(11, 23)
0x800400200100080040020010008004002001f927c9c7663bc8f9d5b785bc2de16ff25
