In [57]:
import numpy as np
from scipy.linalg import null_space
import sympy as sp
from sympy import Poly, symbols, Domain
from sympy import ZZ, QQ
from sympy.polys.domainmatrix import DomainMatrix
from sympy.polys.domains import GF


In [58]:
def cyclicshift(n, k):
    S = np.zeros((n, n), dtype = int)
    for i in range(n):
        S[i, (i+k) % n] = 1
    return S

def y(l, m, k):
    return np.kron(np.identity(l, dtype=int), cyclicshift(m, k))

def x(l, m, k):
    return np.kron(cyclicshift(l, k), np.identity(m, dtype=int))


In [59]:

def ker_of(arr):
    dm = DomainMatrix(arr.tolist(), arr.shape, domain=GF(2))
    return np.array(dm.nullspace().to_Matrix())
def nparr_to_lean(arr):
    s = "!!["
    for row in arr:
        for elem in row:
            s = s + str(elem)+","
        s = s[:-1] + ";\n"
    s = s + "]"
    return s


In [97]:
l = 6
m = 6
x(l, m, 3) + y(l, m, 3)
BB_72_A = x(l, m, 3)+y(l, m, 1)+y(l, m, 2)
BB_72_B = y(l, m, 3)+x(l, m, 1)+x(l, m, 2)
H_x = np.hstack((BB_72_A, BB_72_B))
H_z = np.hstack((BB_72_B.transpose(), BB_72_A.transpose()))


In [61]:
l = 4
m = 4
BB_32_A = x(l, m, 3)+y(l, m, 1)+y(l, m, 2)
BB_32_B = y(l, m, 3)+x(l, m, 1)+x(l, m, 2)
H_x_32 = np.hstack((BB_32_A, BB_32_B))
H_z_32 = np.hstack((BB_32_B.transpose(), BB_32_A.transpose()))

In [62]:

#print(nparr_to_lean(ker_of(H_z)))
print(ker_of(H_x))

[[1 1 0 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [1 0 0 ... 0 0 1]]


In [63]:
q9x = np.array([[1, 1, 1, 1, 1, 1, 0, 0, 0], [0, 0, 0, 1, 1, 1, 1, 1, 1]])
q9z = np.array([[1, 1, 0, 0, 0, 0, 0, 0, 0],[0, 1, 1, 0, 0, 0, 0, 0, 0],[0, 0, 0, 1, 1, 0, 0, 0, 0],
  [0, 0, 0, 0, 1, 1, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 1, 1, 0],
  [0, 0, 0, 0, 0, 0, 0, 1, 1]
])
print(nparr_to_lean(ker_of(q9z)))

!![1,1,1,0,0,0,0,0,0;
0,0,0,1,1,1,0,0,0;
0,0,0,0,0,0,1,1,1;
]


In [64]:
steane = np.array([[1, 0, 0, 1, 0, 1, 1],
                    [0, 1, 0, 1, 1, 0 , 1],
                      [0, 0, 1, 0, 1, 1, 1]])
print(nparr_to_lean(ker_of(steane)))

!![1,1,0,1,0,0,0;
0,1,1,0,1,0,0;
1,0,1,0,0,1,0;
1,1,1,0,0,0,1;
]


In [65]:
golay = np.array([
    [0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],[
1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],[
0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],[
1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],[
1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],[
1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],[
0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],[
0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],[
0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],[
1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],[
1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

])

print(nparr_to_lean(ker_of(golay)))

!![1,1,0,0,0,1,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0;
0,1,1,0,0,0,1,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0;
1,1,1,1,0,1,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0;
0,1,1,1,1,0,1,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0;
0,0,1,1,1,1,0,1,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0;
1,1,0,1,1,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0;
0,1,1,0,1,1,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0;
0,0,1,1,0,1,1,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0;
1,1,0,1,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0;
1,0,1,0,1,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0;
1,0,0,1,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,1,0;
1,0,0,0,1,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1;
]


In [66]:
def matrix_to_nat(matrix):
    # 1. Flatten the m x n matrix into a 1D array of m*n indices
    # 'C' order (row-major) is standard: [row0, row1, ...]
    flattened = np.array(matrix).astype(int)[::-1,::-1].flatten()
    
    # 2. Convert the bits to a binary string
    bit_string = ''.join(map(str, flattened))
    
    # 3. Convert binary string to a natural number (base 2)
    natural_number = int(bit_string, 2)
    
    return hex(natural_number), natural_number, bit_string

def nat_to_matrix(n, shape):
    # 1. Determine the total number of elements
    rows, cols = shape
    total_elements = rows * cols
    
    # 2. Convert natural number back to binary string
    # We use zfill to ensure leading zeros aren't lost
    bit_string = bin(n)[2:].zfill(total_elements)
    
    # 3. Convert string of bits back to a 1D numpy array
    flattened = np.array([int(bit) for bit in bit_string])
    
    # 4. Reshape to the original matrix dimensions
    matrix = flattened.reshape(rows, cols)
    
    # 5. Reverse the flips [::-1, ::-1] performed in the encoding function
    # This restores the original row and column order
    original_matrix = matrix[::-1, ::-1]
    
    return original_matrix


In [67]:
print(matrix_to_nat(steane))
print(matrix_to_nat(ker_of(steane)))

('0x1d2d69', 1912169, '111010010110101101001')
('0x8e94b0b', 149506827, '1000111010010100101100001011')


In [95]:
print(matrix_to_nat(H_x))
print(matrix_to_nat(H_z))
print(matrix_to_nat(ker_of(H_x)))
print(matrix_to_nat(ker_of(H_z)))
print(H_x.shape)

('0x1000008200c0020000080000410840010000040000208c0000800080000010460000400040000008230000200020000004118000100080400002000300080040200001002100040020100000803000020012000000401800010009000000200c0000800480000010060000408201000000000c0020410080000000840010208040000000c0000810480000000060000408240000000030000204120000000018000102080400080000300001040200040002100000820100020003000000412000010001800000209000008000c0000010480000400060000008201000200000c0000410080010000840000208040008000c0000010480000400060000008240000200030000004120000100018000002080400080000300001040200040002100000820100020003000000412000010001800000209000008000c000001048000040006', 116313195860342676972032250591852547443092911862770324096852246529452441337834720636643965878995648550484493911918580264056762933552765668383201080946703576039518272134483809924170660497361586742142415009489138798281728630694279113062649486247817125164504153419586558689882820268555480177465972065366250663649007011269319677764312536499958545449

In [ ]:
bad_at = nat_to_matrix(511573285218915395314361290799996539799732979402594217106366345234325512703427101034892065503154672001381584613885638895476976630314394572357065150877393061218072869376932474598684800846405448537837621564330650710192080997651956248520360119079516056005284456878920904916768302876161868886747917941037414389588115515596487972459997103098893810393895625829473438809092757764383013065717973040, (36, 36))
print(np.array_equal(np.transpose(BB_72_A.transpose), bad_hat))

False


In [14]:
def greedy_independent_rows(matrix):
    """
    Greedily selects rows from top to bottom that are linearly 
    independent over F2.
    """
    num_rows, num_cols = matrix.shape
    
    selected_indices = []
    basis = [] # Stores the rows that form our current basis

    for i in range(num_rows):
        row = matrix[i].copy()
        
        # Reduce the current row using the basis already found
        for b in basis:
            # If the row has a 1 at the pivot position of the basis row, XOR them
            # This is the standard Gaussian elimination step over F2
            pivot = np.argmax(b == 1)
            if row[pivot] == 1:
                row = (row + b) % 2
        
        # If the row is not all zeros after reduction, it is independent
        if np.any(row):
            selected_indices.append(i)
            # Add to basis and keep basis in row-echelon form for efficiency
            basis.append(row)
            # Optional: Sort basis by leading coefficient (pivot) to speed up reduction
            basis.sort(key=lambda x: np.argmax(x == 1))

    return selected_indices, matrix[selected_indices]

In [101]:
H_x_rows = greedy_independent_rows(H_x)[0]
H_x_submat = matrix_to_nat(H_x[H_x_rows])
print(H_x_submat)

('0x40000008230000200020000004118000100020100000803000020012000000401800010009000000200c0000800480000010060000408201000000000c0020410080000000840010208040000000c0000810480000000060000408240000000030000204120000000018000102080400080000300001040200040002100000820100020003000000412000010001800000209000008000c0000010480000400060000008201000200000c0000410080010000840000208040008000c0000010480000400060000008240000200030000004120000100018000002080400080000300001040200040002100000820100020003000000412000010001800000209000008000c000001048000040006', 419498725932221245461803539908156625663508981539479044207518206318869105285898980216749273687331082424761064835645907704250050671571202704467724235010258610388124563025533510050850173033055246484701792488043694126959480501302261334404983724029046959917145687178911475685640571728227411911149426633027765835003387088977903707839963819224272303278164636647584589948823816382122100082233663986843854052783058948278805720700320497228697560144682010887589614

In [103]:
H_z_rows = greedy_independent_rows(H_z)[0]
H_z_submat = matrix_to_nat(H_z[H_z_rows])
print(H_z_submat)
print(H_z_rows)


('0x840002000402080000c000010002010400000060002000012080000030001000201040000210000800100820000300000400080410000006000200001208000003000100000904000001800080000482000000c0004000804100000840002000402080000c0000100020104080001800000000482040000c0000000024102000060000000012081000030000000201040800210000000100820400300000000080410200006008000001200100003004000000900080001802000000480040000c0100000804002000840080000402001000c0004000020100080001882000000400040000c410000002000200006208000001000100003104000020000080021082000010000040030041000008', 865216315717372029447069625593739329083816353994370576599144708118067254492506802504104823531526619645877244264604341847773879971375543681726731403786930115854395060758833866932806473649407744896919034320520487886849023242835527192829877737580871791183845741735430529667291824682380645036710693073993648185307310164060587175416936889594405774652547891471036856995442101196988536928372903921529883248040420520382444268692176659055169627658757971869559348

In [20]:
def matrix_to_lean(mat):
    s = "!!["
    for row in mat:
        for elem in row:
            s+=str(elem) + ", "
        s=s[:-2] + ";\n"
    s=s[:-2]+"]"
    return s

In [22]:
print(matrix_to_lean(ker_of(golay)))

!![1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0;
0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0;
0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0;
1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0;
0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0;
0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0;
1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0;
1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0;
1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0;
1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
