In [1]:
import numpy as np
from scipy.linalg import null_space
import sympy as sp
from sympy import Poly, symbols, Domain
from sympy import ZZ, QQ
from sympy.polys.domainmatrix import DomainMatrix
from sympy.polys.domains import GF


In [2]:
def cyclicshift(n, k):
    S = np.zeros((n, n), dtype = bool)
    for i in range(n):
        S[i, (i+k) % n] = True
    return S

def y(l, m, k):
    return np.kron(np.identity(l), cyclicshift(m, k))

def x(l, m, k):
    return np.kron(cyclicshift(l, k), np.identity(m))


In [3]:

def ker_of(arr):
    dm = DomainMatrix(arr.tolist(), arr.shape, domain=GF(2))
    return np.array(dm.nullspace().to_Matrix())
def nparr_to_lean(arr):
    s = "!!["
    for row in arr:
        for elem in row:
            s = s + str(elem)+","
        s = s[:-1] + ";\n"
    s = s + "]"
    return s


In [4]:
l = 6
m = 6
x(l, m, 3) + y(l, m, 3)
BB_72_A = x(l, m, 3)+y(l, m, 1)+y(l, m, 2)
BB_72_B = y(l, m, 3)+x(l, m, 1)+x(l, m, 2)
H_x = np.hstack((BB_72_A, BB_72_B))
H_z = np.hstack((BB_72_B.transpose(), BB_72_A.transpose()))


In [5]:
l = 4
m = 4
BB_72_A = x(l, m, 3)+y(l, m, 1)+y(l, m, 2)
BB_72_B = y(l, m, 3)+x(l, m, 1)+x(l, m, 2)
H_x = np.hstack((BB_72_A, BB_72_B))
H_z = np.hstack((BB_72_B.transpose(), BB_72_A.transpose()))

In [6]:

#print(nparr_to_lean(ker_of(H_z)))
print(ker_of(H_x))

[[0 1 1 0 1 1 1 0 1 1 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 1 1 1 0 1 1 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 1 1 0 1 1 1 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 1 1 0 1 1 1 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 1 0 1 1 1 0 1 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 1 1 0 1 1 1 0 1 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 1 0 0 1 1 0 1 1 1 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 1 1 0 0 1 1 0 1 1 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 1 0 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 1 1 1 1 0 0 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [1 0 1 1 0 1 0 0 1 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [1 1 0 1 0 0 1 0 1 1 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [1 1 1 0 1 1 1 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 1 1 1 0 1 1 1 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [1 0 1 1 1 0 1 1 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [7]:
q9x = np.array([[1, 1, 1, 1, 1, 1, 0, 0, 0], [0, 0, 0, 1, 1, 1, 1, 1, 1]])
q9z = np.array([[1, 1, 0, 0, 0, 0, 0, 0, 0],[0, 1, 1, 0, 0, 0, 0, 0, 0],[0, 0, 0, 1, 1, 0, 0, 0, 0],
  [0, 0, 0, 0, 1, 1, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 1, 1, 0],
  [0, 0, 0, 0, 0, 0, 0, 1, 1]
])
print(nparr_to_lean(ker_of(q9z)))

!![1,1,1,0,0,0,0,0,0;
0,0,0,1,1,1,0,0,0;
0,0,0,0,0,0,1,1,1;
]


In [8]:
steane = np.array([[1, 0, 0, 1, 0, 1, 1],
                    [0, 1, 0, 1, 1, 0 , 1],
                      [0, 0, 1, 0, 1, 1, 1]])
print(nparr_to_lean(ker_of(steane)))

!![1,1,0,1,0,0,0;
0,1,1,0,1,0,0;
1,0,1,0,0,1,0;
1,1,1,0,0,0,1;
]


In [9]:
golay = np.array([
    [0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],[
1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],[
0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],[
1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],[
1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],[
1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],[
0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],[
0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],[
0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],[
1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],[
1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

])

print(nparr_to_lean(ker_of(golay)))

!![1,1,0,0,0,1,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0;
0,1,1,0,0,0,1,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0;
1,1,1,1,0,1,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0;
0,1,1,1,1,0,1,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0;
0,0,1,1,1,1,0,1,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0;
1,1,0,1,1,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0;
0,1,1,0,1,1,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0;
0,0,1,1,0,1,1,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0;
1,1,0,1,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0;
1,0,1,0,1,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0;
1,0,0,1,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,1,0;
1,0,0,0,1,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1;
]


In [10]:
def matrix_to_nat(matrix):
    # 1. Flatten the m x n matrix into a 1D array of m*n indices
    # 'C' order (row-major) is standard: [row0, row1, ...]
    flattened = np.array(matrix).flatten()
    
    # 2. Convert the bits to a binary string
    bit_string = ''.join(map(str, flattened))
    
    # 3. Convert binary string to a natural number (base 2)
    natural_number = int(bit_string, 2)
    
    return natural_number, bit_string

def serialize_matrix(M):
  s = 0
  for k in range(M.shape[0] * M.shape[1]):
    i = k % M.shape[0]
    j = int(k / M.shape[0])
    if M[i, j]:
      s += (1 << k)
  return s

In [11]:
print(hex(serialize_matrix(H_z)))
print(H_z.shape)
print(hex(serialize_matrix(ker_of(H_x))))
print(ker_of(H_x).shape)

0x38009400c2006100038009400c2006100038009400c2006180034009200c10064088204410228011840842042102180188404420221011800884044202210118
(16, 32)
0x80004000200010000800040002000100008000400020001000080004000200016ee137789bb4cdd216ee837749bb2cdde16e7837b49bd2cdee167783bb49dd2c
(16, 32)


In [12]:
print(hex(serialize_matrix(steane)))
print(steane.shape)
print(hex(serialize_matrix(ker_of(steane))))
print(ker_of(steane))

0x1ee711
(3, 7)
0x8421ebd
[[1 1 0 1 0 0 0]
 [0 1 1 0 1 0 0]
 [1 0 1 0 0 1 0]
 [1 1 1 0 0 0 1]]


In [22]:
print(hex(serialize_matrix(golay)))
print(golay.shape)
print(hex(serialize_matrix(ker_of(golay))))


0x40100401004010040100401004008eb27ea5ee3366d9b661ed7b5ed18ee3a
(11, 23)
0x800400200100080040020010008004002001f927c9c7663bc8f9d5b785bc2de16ff25
